// <auto-generated />
namespace SwiftDev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class nouserstillemployed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nouserstillemployed));
        
        string IMigrationMetadata.Id
        {
            get { return "201504122134477_nouserstillemployed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
